parameters:
    env(DATABASE_APPBOX_URL): 'mysql://root:toor@127.0.0.1:3306/ab_master'
    env(DATABASE_DATABOX_URL): 'mysql://root:toor@127.0.0.1:3306/db_master'

doctrine:
    dbal:
        default_connection: appbox
        connections:
            appbox:
                url: '%env(DATABASE_APPBOX_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            databox:
                url: '%env(DATABASE_DATABOX_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
