index:
    path: /
    controller: App\Controller\DefaultController::index

test:
    path: /test
    controller: App\Controller\DefaultController::test

showUsers:
    path: /users
    controller: App\Controller\DefaultController::showUsers
